export const rows = [
  [
    { bonus: 'TW' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: 'TW' },
  ],
  [
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: 'TW' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: '★' }, // Center star
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: 'TW' },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
  ],
  [
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
  ],
  [
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DW' },
    { bonus: null },
  ],
  [
    { bonus: 'TW' },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'TW' },
    { bonus: null },
    { bonus: null },
    { bonus: null },
    { bonus: 'DL' },
    { bonus: null },
    { bonus: null },
    { bonus: 'TW' },
  ],
];
